# specify the repos, and the trigger for starting the build
resources:
  repositories:
    - repository: skillpredict
      type: git
      name: SkillPredict/skillpredict
      ref: dev
      trigger:
        branches:
          include:
            - dev
        paths:
          include:
            - sp-web-2

    - repository: skillpredict-devops
      type: git
      name: SkillPredict/skillpredict-devops
      ref: master
      trigger:
        - none

# Dev Ops Library/Variable groups to use
# Set Env variables at build time
variables:
  - template: variables/dev.yaml

# Agent Pool
pool:
  vmImage: $(vmImageName)

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - template: app-build.yaml

  - stage: Deploy
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: Deploy
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: storybook-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: app-deploy.yaml
